import Link from "next/link";

export function Footer() {
  return (
      <footer className="border-t border-neutral-800 bg-neutral-950 py-12 mt-24">
            <div className="mx-auto max-w-6xl px-6">
                    <div className="grid gap-8 sm:grid-cols-4">
                              <div>
                                          <div className="mb-4 text-2xl font-bold text-indigo-400">Lisan</div>
                                                      <p className="text-sm text-neutral-500">منصة ترجمة الفيديو بالذكاء الاصطناعي.</p>
                                                                </div>
                                                                          <div>
                                                                                      <div className="mb-3 font-bold">المنتج</div>
                                                                                                  <ul className="space-y-2 text-sm text-neutral-400">
                                                                                                                <li><Link href="/new">ابدأ الترجمة</Link></li>
                                                                                                                              <li><Link href="/pricing">الأسعار</Link></li>
                                                                                                                                          </ul>
                                                                                                                                                    </div>
                                                                                                                                                              <div>
                                                                                                                                                                          <div className="mb-3 font-bold">الشركة</div>
                                                                                                                                                                                      <ul className="space-y-2 text-sm text-neutral-400">
                                                                                                                                                                                                    <li><Link href="/about">من نحن</Link></li>
                                                                                                                                                                                                                  <li><Link href="/privacy">الخصوصية</Link></li>
                                                                                                                                                                                                                              </ul>
                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                              <div className="mb-3 font-bold">تواصل</div>
                                                                                                                                                                                                                                                                          <ul className="space-y-2 text-sm text-neutral-400">
                                                                                                                                                                                                                                                                                        <li>hello@lisan.app</li>
                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                              <div className="mt-12 border-t border-neutral-800 pt-6 text-center text-xs text-neutral-500">
                                                                                                                                                                                                                                                                                                                                        © 2025 Lisan
                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                          </footer>
                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                            